/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.16.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as embeddings from "../embeddings";
import type * as lib_crud from "../lib/crud";
import type * as lib_migrations from "../lib/migrations";
import type * as lib_relationships from "../lib/relationships";
import type * as pinecone from "../pinecone";
import type * as texts from "../texts";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  embeddings: typeof embeddings;
  "lib/crud": typeof lib_crud;
  "lib/migrations": typeof lib_migrations;
  "lib/relationships": typeof lib_relationships;
  pinecone: typeof pinecone;
  texts: typeof texts;
}>;
